In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
##Removing irrelevant columns

df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
#Encode Categorical Features
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [7]:
df.head(20)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0
10,528,France,1,31,6,102016.72,2,0,0,80181.12,0
11,497,Spain,1,24,3,0.00,2,1,0,76390.01,0
12,476,France,0,34,10,0.00,2,1,0,26260.98,0
13,549,France,0,25,5,0.00,2,0,0,190857.79,0
14,635,Spain,0,35,7,0.00,2,1,1,65951.65,0
15,616,Germany,1,45,3,143129.41,2,0,1,64327.26,0
16,653,Germany,1,58,1,132602.88,1,1,0,5097.67,1
17,549,Spain,0,24,9,0.00,2,1,1,14406.41,0
18,587,Spain,1,45,6,0.00,1,0,0,158684.81,0
19,726,France,0,24,6,0.00,2,1,1,54724.03,0

In [8]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoded = onehot_encoder_geo.fit_transform(df[['Geography']])

In [9]:
geo_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [12]:
##combine the encoded columns with the original dataframe
df = pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [13]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [14]:
#save encoder and scaler 
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [15]:
#Divide the dataset into independent and dependent variables

X = df.drop('Exited', axis=1)
y = df['Exited']

## Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

standard_scaler = StandardScaler()

X_train_scaler = standard_scaler.fit_transform(X_train)
X_test_scaler = standard_scaler.transform(X_test)

In [16]:
with open('standard_scaler.pkl', 'wb') as file:
    pickle.dump(standard_scaler, file)

In [17]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

## ANN Implementaation

In [18]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [19]:
#Build our own ANN model
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train_scaler.shape[1],)), ## first Hidden Layer connected with input layer
        Dense(32, activation='relu'), ## second Hidden Layer
        Dense(1, activation='sigmoid') ## output layer
    ])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
opt= tf.keras.optimizers.Adam(learning_rate=0.001)
loss = tf.keras.losses.BinaryCrossentropy()

In [22]:
#compile the model 
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [24]:
##set up the tensorboard 

from datetime import datetime
log_dir = "logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [ ]:
## Setup Early Stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [28]:
## Train the model 
history = model.fit(
    X_train_scaler, y_train,
    epochs=100,
    validation_data=(X_test_scaler, y_test),
    callbacks=[early_stopping, tensorboard_callback]

)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3206 - accuracy: 0.8658 - val_loss: 0.3422 - val_accuracy: 0.8605
Epoch 2/100
250/250 [==============================] - 0s 992us/step - loss: 0.3203 - accuracy: 0.8683 - val_loss: 0.3376 - val_accuracy: 0.8650
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3170 - accuracy: 0.8661 - val_loss: 0.3406 - val_accuracy: 0.8560
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3169 - accuracy: 0.8689 - val_loss: 0.3405 - val_accuracy: 0.8600
Epoch 5/100
250/250 [==============================] - 0s 990us/step - loss: 0.3147 - accuracy: 0.8701 - val_loss: 0.3571 - val_accuracy: 0.8520
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8698 - val_loss: 0.3380 - val_accuracy: 0.8650
Epoch 7/100
250/250 [==============================] - 0s 997us/step - loss: 0.3125 - accuracy: 0.8692 - val_loss: 0.3425 - val_accuracy: 0.8590

In [29]:
model.save('model.h5')

c:\Users\DEEP\OneDrive\Documents\Machine Learning Projects\MLPROJECT-END-TO-END\venv\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [35]:
# Load TensorBoard Extension 
%reload_ext tensorboard

In [36]:
%tensorboard --logdir logs/fit/20260628-222049

Reusing TensorBoard on port 6006 (pid 31260), started 0:00:33 ago. (Use '!kill 31260' to kill it.)

In [ ]:
## load Pickle files