In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle

In [5]:
# load the pickle Files
model = load_model('model.h5')

with open('standard_scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

with open('onehot_encoder_geo.pkl', 'rb') as f:
    encoder = pickle.load(f)

with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

In [7]:
#Example input data for prediction
input_data = {
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [8]:
geo_encoded = encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=encoder.get_feature_names_out(['Geography']))

c:\Users\DEEP\OneDrive\Documents\Machine Learning Projects\MLPROJECT-END-TO-END\venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [9]:
input_data = pd.DataFrame([input_data])

In [10]:
input_data = pd.concat([input_data.reset_index(drop=True),geo_encoded_df],axis=1)
input_data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [11]:
#Encode categorical variables
input_data['Gender'] = label_encoder.transform(input_data['Gender'])

In [ ]:
## Concatentate the encoded columns with the original DataFrame
input_df = input_data.drop('Geography', axis=1)

In [13]:
input_df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [14]:
input_scaled = scaler.transform(input_df)

In [15]:
##Prediction Churn 

predictions = model.predict(input_scaled)

print(predictions)

1/1 [==============================] - 0s 136ms/step
[[0.03416349]]

In [18]:
predictions_proba = predictions[0][0]

In [19]:
predictions_proba

0.034163494

In [20]:
if predictions_proba > 0.5:
    print("The customer is likely to churn.")
else:   
    print("The customer is not likely to churn.")

The customer is not likely to churn.